### ISSUE TITLE
Can't find Gendaymtx.exe (Dynamo)

### ISSUE THREAD

**Issue by JeroenBg** [mostaphaRoudsari/honeybee#657]
Hi,

I am trying to run the sample file "05_annual_radiation_gridbased.dyn" in Dynamo, with an epw-file for Amsterdam, but the Run Radiance Analysis node reports an error, stating it can't find Gendaymtx.exe

I've downloaded the file manually and:
1. placed it in the designated folder directory where the node writes the data (tried both c:/ladybug and d:/ladybug; using corporate laptop and maybe writing/reading in C is somehow restricted)
2. placed the file in user>appdata>roaming etc, in the honeybee and ladybug folders.

still it shows me the same error. Does anyone have an idea what I'm doing wrong here?

**ERRReport:**

_[0] ERROR:

Can't find gendaymtx.exe.
Use radbinPath method to set the path to Radiance binaries before executing the command.

If you think this is a bug submit an issue on github.
https://github.com/ladybug-tools/honeybee-dynamo/issues
and include below error message:

Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "C:\Users\biggej\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\radiation\gridbased.py", line 128, in write
    skycommands, skyfiles = getCommandsRadiationSky(
  File "C:\Users\biggej\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\recipedcutil.py", line 155, in getCommandsRadiationSky
    gdm = skymtxToGendaymtx(skyMatrix, projectFolder)
  File "C:\Users\biggej\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\recipe\recipedcutil.py", line 862, in skymtxToGendaymtx
    gdm = Gendaymtx(outputName=skyMtx, weaFile=weaFilepath)
  File "C:\Users\biggej\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\gendaymtx.py", line 66, in __init__
    RadianceCommand.__init__(self)
  File "C:\Users\biggej\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 18, in __init__
    self.radbinPath = config.radbinPath
  File "C:\Users\biggej\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 52, in radbinPath
    self.__checkExecutable(radbinPath=path, raiseException=True)
  File "C:\Users\biggej\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Honeybee\extra\honeybee\radiance\command\_commandbase.py", line 150, in _RadianceCommand__checkExecutable
    raise ValueError(__err)
ValueError: Can't find gendaymtx.exe.
Use radbinPath method to set the path to Radiance binaries before executing the command._

**Comment by mostaphaRoudsari** [comment]
The error shows that Radiance is not installed on your system. Install Radiance from [here](https://github.com/NREL/Radiance/releases/tag/5.1.0) to `c:\radiance`, and try again.

**Comment by JeroenBg** [comment]
Thanks for the quick response, its working now!
